sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - travis-after-all && npm run semantic-release
env:
  global:
    - secure: oHccwxpkI3SU+EPMmKX1dLzP5Y93AyqdPjqXIu07O+SbWGXPJsyVJAFM0sGMcB4VF5M5tfmkv8koXJa1TIGagmsK/Y5/frn8ts8TMpjeteafY1jk65sNaYd2720bVt9f+VAszsSk2CTZf5jvM04ixVTYIBu4xKHt7lfDQpdVgbq6GNIdl4uHcPHrTZLcfMouIIQnJREKpu8P4Qpa4xuyKLQIGmWTOUtm5Ud89AJbN/+mV2/ie6NxlumZWYEZ+9gC7mOV4StcZMEUp4BZObNBbI5kXJK7NF4+T7XrQP8GprDUMedV/HqIAJmFEYa5u5c/3Z4fMEK8IcBJAe8lYj4/g6IN9t7/DRTrjqWJUBmIjiStYcZtXUil6NnvFtdBzS0QJ92ShCvpz8cnMiPIEZ9VPUcJ7BTRVS/lcZcLNOnoY5cqcs7maAgbKjLLfEWwldXdJY5i1ZtGFclQUHorqCONmcQqHPrBwxeKtMLkq0hDZ5OIpaXhHG9ZJjDWXGeukMwa7GYOJ6oJfvt4HiUNUzIffiAVWGFNOwZUqLNf9JhAQ9rlC07O8EozzCUo9KpHxIdDXsvzaaRPqdTPPvWPLx6432MmYR6yq5RckOX/c5Zd+KXkBRsFlkhl5oXCIXsn4VqVZFpEeURgGw8mtbtss2eprpYuJktfqUugv9Kni2UT31Y=
    - secure: xUwnPAmo6g1un4D262MWIo5Y3ZjnY8/DJgq9Oeb1siZEZMp4EBT6pnRVzMRWXusBZ2jHy5GkxUl1Vx8MkSPWl0l6TxRojDtQ+1zbxtdPaFocWJDECPPaDQ3bCGcW8Oy75zYPC2qOKugD976vJPUx6tktjx5DBUF6RFl0rSjEe8TaLIdv0nlRM1nljSK9jvVIigxUViSHHIE66qiZQ1btxCJ+XGt5F8FqMKl82wRkrugRRPxU9apshCZqLhRjg4dlZWaHu5a2GlJzUgv2WAd5RAwRugsxVX23YbmxJ3o2dH/fZX57Hjn7TA62s+P1VEQ2dojGqn+54BmXWnoNd56lIq8HikskxzGXgDQ7XJdTk7qegHXmk5xArTjGN/XZ1s3djxtjz2Lr/yzIEbAweAS4E+osrq3sJexHttrAXOUJ2Ru1Zss6Kx9Ei+ye1qEATlil73OJ06EKzGgBpxn+dwGQVrxk5AixdB8C/32TUIHJpPLQTQv5qOXUc39TbAnT6nVjr+ML8b1qVaQpuYlmUpO4Hnc9kkD9yH5YizgkgvCtghRHzZ5Tc9CouXzRAtDzUAUO1Sk/IEGMuo2nAfXGp3zDrr5m2ZdW965KkyiieFECO1q79JX1b0gkhjOJWT4Dn8XUvsepKL03toTjZeNr2tUoGp6whuo+5DNnHJIi99cuqzc=
